// <auto-generated />
using System;
using Inventory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260719065931_InitialInventorySchema")]
    partial class InitialInventorySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inventory.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Inventory.Domain.Entities.CollectionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("FailedIisServerCount")
                        .HasColumnType("int");

                    b.Property<int>("IisServerCount")
                        .HasColumnType("int");

                    b.Property<int>("MatchedConnectionCount")
                        .HasColumnType("int");

                    b.Property<int>("StagedConnectionCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("SuccessfulIisServerCount")
                        .HasColumnType("int");

                    b.Property<int>("UnmatchedConnectionCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status", "StartedAtUtc");

                    b.ToTable("CollectionRuns", (string)null);
                });

            modelBuilder.Entity("Inventory.Domain.Entities.ConnectionInventory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ActiveConnections")
                        .HasColumnType("int");

                    b.Property<string>("AppPoolName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("sysname");

                    b.Property<int>("IdlePooledConnections")
                        .HasColumnType("int");

                    b.Property<int>("IisServerId")
                        .HasColumnType("int");

                    b.Property<string>("IisServerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("InventoryDateUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("SqlEndpoint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SqlInstance")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SqlServerId")
                        .HasColumnType("int");

                    b.Property<string>("SqlServerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("TotalConnections")
                        .HasColumnType("int");

                    b.Property<string>("WorkerProcessIds")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("IisServerId");

                    b.HasIndex("InventoryDateUtc");

                    b.HasIndex("SqlServerId");

                    b.HasIndex("CollectionId", "IisServerId", "AppPoolName", "SqlServerId", "DatabaseName")
                        .IsUnique();

                    b.ToTable("ConnectionInventory", null, t =>
                        {
                            t.HasCheckConstraint("CK_ConnectionInventory_Totals", "[TotalConnections] = [ActiveConnections] + [IdlePooledConnections]");
                        });
                });

            modelBuilder.Entity("Inventory.Domain.Entities.IisConnectionStaging", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AppPoolName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasColumnType("varchar(48)");

                    b.Property<int>("ClientPort")
                        .HasColumnType("int");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IisServerId")
                        .HasColumnType("int");

                    b.Property<string>("IisServerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessingStartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte>("ProcessingStatus")
                        .HasColumnType("tinyint");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("SqlServerIp")
                        .IsRequired()
                        .HasColumnType("varchar(48)");

                    b.Property<int>("SqlServerPort")
                        .HasColumnType("int");

                    b.Property<int>("WorkerProcessId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IisServerId");

                    b.HasIndex("ProcessingStatus", "CollectionId", "SqlServerIp");

                    b.HasIndex("CollectionId", "IisServerId", "AppPoolName", "WorkerProcessId", "ClientIp", "ClientPort", "SqlServerIp", "SqlServerPort")
                        .IsUnique();

                    b.ToTable("IisConnectionStaging", null, t =>
                        {
                            t.HasCheckConstraint("CK_IisConnectionStaging_SqlServerPort", "[SqlServerPort] = 1433");
                        });
                });

            modelBuilder.Entity("Inventory.Domain.Entities.IisServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CollectionIntervalSeconds")
                        .HasColumnType("int");

                    b.Property<int>("ConnectionTimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Fqdn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastCollectionAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("LastCollectionStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("LastSuccessfulCollectionUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ServerName")
                        .IsUnique();

                    b.ToTable("IisServers", null, t =>
                        {
                            t.HasCheckConstraint("CK_IisServers_CollectionInterval", "[CollectionIntervalSeconds] BETWEEN 10 AND 86400");

                            t.HasCheckConstraint("CK_IisServers_ConnectionTimeout", "[ConnectionTimeoutSeconds] BETWEEN 5 AND 300");
                        });
                });

            modelBuilder.Entity("Inventory.Domain.Entities.SqlServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConnectionTimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Fqdn")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("varchar(48)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<byte?>("LastConnectionStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("TrustServerCertificate")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress")
                        .IsUnique();

                    b.ToTable("SqlServers", null, t =>
                        {
                            t.HasCheckConstraint("CK_SqlServers_ConnectionTimeout", "[ConnectionTimeoutSeconds] BETWEEN 5 AND 300");

                            t.HasCheckConstraint("CK_SqlServers_Port", "[Port] = 1433");
                        });
                });

            modelBuilder.Entity("Inventory.Domain.Entities.UnknownSqlEndpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("varchar(48)");

                    b.Property<string>("LastIisServerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("ObservationCount")
                        .HasColumnType("bigint");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress", "Port")
                        .IsUnique();

                    b.ToTable("UnknownSqlEndpoints", null, t =>
                        {
                            t.HasCheckConstraint("CK_UnknownSqlEndpoints_Port", "[Port] = 1433");
                        });
                });

            modelBuilder.Entity("Inventory.Domain.Entities.ConnectionInventory", b =>
                {
                    b.HasOne("Inventory.Domain.Entities.CollectionRun", "CollectionRun")
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Inventory.Domain.Entities.IisServer", "IisServer")
                        .WithMany()
                        .HasForeignKey("IisServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Inventory.Domain.Entities.SqlServer", "SqlServer")
                        .WithMany()
                        .HasForeignKey("SqlServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CollectionRun");

                    b.Navigation("IisServer");

                    b.Navigation("SqlServer");
                });

            modelBuilder.Entity("Inventory.Domain.Entities.IisConnectionStaging", b =>
                {
                    b.HasOne("Inventory.Domain.Entities.CollectionRun", "CollectionRun")
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory.Domain.Entities.IisServer", "IisServer")
                        .WithMany()
                        .HasForeignKey("IisServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CollectionRun");

                    b.Navigation("IisServer");
                });
#pragma warning restore 612, 618
        }
    }
}
